### PR TITLE
[BUGFIX] Skip wrong formatted lines

### LINKED ISSUE #3: Comments for conditions result in PHP warning
When you comment a condition out in .editorconfig, like:

```
#[*.md]
```

The following warning is thrown:
> PHP Warning:  syntax error, unexpected END_OF_LINE, expecting '=' in Unknown on line 40
> in /var/www/html/vendor/idiosyncratic/editorconfig/src/EditorConfigFile.php on line 130

It only happens when a comment is on the condition part. This works as expected:
```
[*.md]
#indent_size = 4
```

Thanks!

### PR DESCRIPTION
**Pull request by sabbelasichon**
Resolves: #3

### CODE REVIEW

File: src/EditorConfigFile.php [hunk 1]
```diff
@@ -145,4 +146,24 @@ private function parseIniString(string $content) : array
...
+                }
+
+                $content .= $line;
+            }
+
+            fclose($handle);
+        }
+
+        return $content;
+    }
```
Comment (jcsilkey) [inline src/EditorConfigFile.php:152]: According to the EditorConfig spec:

> Comment: starts with a ; or a #.
> Inserting a # or ; after non-whitespace characters in a line (i.e., inline) shall neither be parsed as a comment nor as part of > the section name, pair (defined below) key or value in which it was inserted. This may change in the future; thus, is not recommended.

While this works to solve lines that start with a `#`, it will also remove lines with a trailing comment (which is technically not a comment at all according to the spec, but still).

I think it would be more correct to strip everything from `#` to the end of the line, something like:

```
    private function cleanContent(string $path) : string
    {
        $content = file_get_contents($path);

        $content = preg_replace('/#.*$/m', '', $content) ?? $content;

        return $content;
    }
```

Thoughts?

Comment (sabbelasichon) [reply src/EditorConfigFile.php:152]: Thanks for elaborating. Looks good to me and works perfectly.

**Review by jcsilkey — APPROVED** [review]
LGTM
